# -*- coding: utf-8 -*-
"""KelasB_Kelompok9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSuZAG3D1Kp9BHge9u7hHDp0hVefpJXD

## ***NOTEBOOK PERHITUNGAN PROJECT ANALISIS PORTOFOLIO PADA SAHAM 035900.KQ 041510.KQ 173940.KQ 122870.KQ***


Oleh:

Aliifah Farhah Maajidah
(L0225014)

Fathia Salsabila Arfian
(L0225021)

# **Import sys**
"""

import sys
!{sys.executable} -m pip install pandas pandas-datareader matplotlib seaborn plotly-express numpy
print("Semua pustaka yang diperlukan telah diinstal.")

"""# **Impor semua pustaka**"""

import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import seaborn as sns
import plotly_express as px
import numpy as np
import yfinance as yf
import datetime

print("Semua pustaka yang diperlukan telah diimpor.")

"""Mengimpor `yfinance` sebagai`yf` dan menggunakan fungsi download-nya untuk mendapatkan harga `'Adj Close'`, kemudian menampilkan lima baris pertama dan informasi dari DataFrame yang dihasilkan.

# **Akuisisi Data Keuangan**
"""

# 1. Tentukan daftar simbol ticker saham
tickers = ['035900.KQ', '041510.KQ', '173940.KQ', '122870.KQ']

# 2. Tentukan tanggal mulai dan tanggal akhir
# end_date = datetime.datetime.now()
end_date = pd.to_datetime('02/07/2025')
start_date = end_date - datetime.timedelta(days=5*365)

# 3. Gunakan yfinance untuk mengunduh data harga saham historis
# Menginisialisasi DataFrame kosong untuk menyimpan 'Adj Close' harga
stock_data_yf = pd.DataFrame()

for ticker in tickers:
    try:
        # Download data for a single ticker
        data = yf.download(ticker, start=start_date, end=end_date, progress=False)
        if not data.empty:
            if 'Adj Close' in data.columns:
                stock_data_yf[ticker] = data['Adj Close']
            elif 'Close' in data.columns:
                # Fallback to 'Close' price if 'Adj Close' is not available (e.g., if auto_adjust makes them identical)
                stock_data_yf[ticker] = data['Close']
                print(f"Warning: 'Adj Close' not found for {ticker}, using 'Close' price.")
            else:
                print(f"Could not find 'Adj Close' or 'Close' data for {ticker}.")
        else:
            print(f"No data downloaded for {ticker}.")
    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")

# Drop any rows with missing values that might occur if some dates are not present for all stocks
stock_data_yf.dropna(inplace=True)

# 4. Tampilkan lima baris pertama dari DataFrame
print("Data harga saham historis (Adj Close) untuk 5 saham:")
print(stock_data_yf.head())

print("\nInformasi DataFrame:\n")
stock_data_yf.info()

"""# **Eksplorasi dan Pra-pemrosesan Data**"""

print("Informasi Ringkas DataFrame stock_data_yf:")
stock_data_yf.info()

print("\nStatistik Deskriptif DataFrame stock_data_yf:")
print(stock_data_yf.describe())

print("\nJumlah Nilai Hilang per Kolom di stock_data_yf:")
print(stock_data_yf.isnull().sum())

"""## **Menghitung *daily returns, monthly returns,* dan normalisasi data saham**

Dengan ME
"""

import numpy as np

# Hitung daily returns
daily_returns = stock_data_yf.pct_change().dropna()

# Hitung monthly returns
# Resample data to get the last trading day of each month and calculate percentage change
monthly_returns = stock_data_yf.resample('ME').last().pct_change().dropna()
# Normalisasi data
# Divide each price by the price on the first day for each stock
normalized_stock_data = stock_data_yf / stock_data_yf.iloc[0]

# Tampilkan lima baris pertama dari daily_returns, monthly_returns, dan normalized_stock_data
print("\nLima Baris Pertama Daily Returns:")
print(daily_returns.head())

print("\nLima Baris Pertama Monthly Returns:")
print(monthly_returns.head())

print("\nLima Baris Pertama Normalized Stock Data:")
print(normalized_stock_data.head())

"""# **Visualisasi Data Awal**"""

import matplotlib.pyplot as plt # Ensure matplotlib is imported for plotting

# 5. Plot the historical adjusted close prices
plt.figure(figsize=(14, 7))
stock_data_yf.plot(ax=plt.gca())
plt.title('Historical Adjusted Close Prices for Selected Stocks')
plt.xlabel('Date')
plt.ylabel('Adjusted Close Price (USD)')
plt.legend(title='Ticker')
plt.grid(True)
plt.tight_layout()
plt.show()

print("Grafik harga saham historis telah ditampilkan.")

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Buat histogram untuk return harian
# daily_returns.hist() automatically creates subplots for each column and returns the Axes objects.
hist_axes = daily_returns.hist(bins=50, figsize=(15, 10)) # Set figsize here

# Get the figure created by daily_returns.hist() to set the suptitle
fig_hist = plt.gcf()
fig_hist.suptitle('Distribusi Daily Returns Saham', y=1.02, fontsize=16)

# Flatten the axes array if it's 2D (e.g., if there are multiple rows of subplots)
if isinstance(hist_axes, (list, np.ndarray)) and len(hist_axes.shape) > 1:
    hist_axes = hist_axes.flatten()

for i, ax in enumerate(hist_axes):
    # Ensure we don't go out of bounds for daily_returns.columns (though hist() should match)
    if i < len(daily_returns.columns):
        ax.set_xlabel('Daily Return')
        ax.set_ylabel('Frequency')
        ax.set_title(f'Daily Returns for {daily_returns.columns[i]}')

plt.tight_layout(rect=[0, 0.03, 1, 0.98]) # Adjust layout to prevent title overlap
plt.show()

print("Histograms untuk daily returns telah ditampilkan.")

# 2. Buat box plot untuk return harian
plt.figure(figsize=(12, 7))
daily_returns.plot(kind='box', ax=plt.gca())
plt.title('Box Plot Daily Returns Saham')
plt.xlabel('Ticker')
plt.ylabel('Daily Return')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Box plots untuk daily returns telah ditampilkan.")

"""## **Visualisasi Data Interaktif**"""

import plotly_express as px

# 1. Buat line plot interaktif untuk normalized_stock_data
fig_normalized_prices = px.line(
    normalized_stock_data,
    x=normalized_stock_data.index,
    y=normalized_stock_data.columns,
    title='Perbandingan Harga Saham yang Dinormalisasi (Interaktif)',
    labels={'index': 'Tanggal', 'value': 'Harga Dinormalisasi'},
    hover_name=normalized_stock_data.columns.name # Display ticker name on hover
)

fig_normalized_prices.update_layout(
    xaxis_title='Tanggal',
    yaxis_title='Harga Dinormalisasi'
)

fig_normalized_prices.show()

print("Line plot interaktif untuk harga saham yang dinormalisasi telah ditampilkan.")

import plotly_express as px

# 2. Buat histogram interaktif untuk daily_returns

print("Membuat histogram interaktif untuk daily returns setiap saham...")

for col in daily_returns.columns:
    fig_hist_daily_returns = px.histogram(
        daily_returns,
        x=col,
        nbins=50, # Number of bins
        title=f'Distribusi Daily Returns Interaktif untuk {col}',
        labels={col: 'Daily Return', 'count': 'Frekuensi'}
    )
    fig_hist_daily_returns.update_layout(xaxis_title='Daily Return', yaxis_title='Frekuensi')
    fig_hist_daily_returns.show()

print("Histogram interaktif untuk daily returns telah ditampilkan.")

"""## **Perhitungan Metrik Portofolio**"""

TRADING_DAYS_PER_YEAR = 252
RISK_FREE_RATE = 0.01 # Asumsi 1% tingkat bebas risiko tahunan

# 2. Hitung Cumulative Return untuk setiap saham
cumulative_returns = (1 + daily_returns).prod() - 1

# 3. Hitung Annual Return untuk setiap saham
# Menggunakan rata-rata aritmetika yang di-annualisasi dari daily returns
annual_returns = daily_returns.mean() * TRADING_DAYS_PER_YEAR

# 4. Hitung Annualized Volatility untuk setiap saham
annualized_volatility = daily_returns.std() * np.sqrt(TRADING_DAYS_PER_YEAR)

# 6. Hitung Sharpe Ratio untuk setiap saham
sharpe_ratios = (annual_returns - RISK_FREE_RATE) / annualized_volatility

# 7. Buat DataFrame untuk menampilkan metrik yang dihitung
portfolio_metrics = pd.DataFrame({
    'Cumulative Return': cumulative_returns,
    'Annual Return': annual_returns,
    'Annualized Volatility': annualized_volatility,
    'Sharpe Ratio': sharpe_ratios
})

print("Metrik Portofolio untuk Setiap Saham:")
print(portfolio_metrics.round(4))

import numpy as np

# 8. Asumsikan bobot yang sama untuk setiap saham dalam portofolio
# Anda bisa memodifikasi bobot ini untuk analisis sensitivitas
num_assets = len(tickers)
weights = np.array([1/num_assets] * num_assets)

# Pastikan bobot yang digunakan memiliki indeks kolom yang sama dengan daily_returns
weights_df = pd.Series(weights, index=daily_returns.columns)

# 9. Hitung daily returns portofolio
portfolio_daily_returns = daily_returns.dot(weights)

# Tampilkan lima baris pertama daily returns portofolio
print("Lima Baris Pertama Daily Returns Portofolio:")
print(portfolio_daily_returns.head())

import numpy as np

# 10. Hitung Cumulative Return Portofolio
portfolio_cumulative_return = (1 + portfolio_daily_returns).prod() - 1

# 11. Hitung Annual Return Portofolio
portfolio_annual_return = portfolio_daily_returns.mean() * TRADING_DAYS_PER_YEAR

# 12. Hitung Annualized Volatility Portofolio
portfolio_annualized_volatility = portfolio_daily_returns.std() * np.sqrt(TRADING_DAYS_PER_YEAR)

# 13. Hitung Sharpe Ratio Portofolio
portfolio_sharpe_ratio = (portfolio_annual_return - RISK_FREE_RATE) / portfolio_annualized_volatility

# 14. Tampilkan metrik portofolio
print("\nMetrik Keseluruhan Portofolio (Bobot Sama):")
print(f"Cumulative Return: {portfolio_cumulative_return:.4f}")
print(f"Annual Return: {portfolio_annual_return:.4f}")
print(f"Annualized Volatility: {portfolio_annualized_volatility:.4f}")
print(f"Sharpe Ratio: {portfolio_sharpe_ratio:.4f}")

"""## **Analisis dan Optimalisasi Portofolio**"""

import numpy as np
import pandas as pd

# 1. Tetapkan jumlah simulasi portofolio
num_portfolios = 10000 # Contoh: 10.000 atau 20.000

# Inisialisasi daftar kosong untuk menyimpan hasil simulasi
portfolio_returns = []
portfolio_volatility = []
portfolio_sharpe_ratios = []
portfolio_weights = []

# Dapatkan jumlah aset dari daily_returns
num_assets = len(daily_returns.columns)

# Hitung rata-rata return harian dan matriks kovarian
mean_daily_returns = daily_returns.mean()
cov_matrix_daily = daily_returns.cov()

# Loop untuk simulasi
for portfolio in range(num_portfolios):
    # a. Hasilkan bobot acak untuk setiap aset
    weights = np.random.random(num_assets)
    weights = weights / np.sum(weights) # Normalisasi agar jumlahnya 1

    portfolio_weights.append(weights)

    # b. Hitung return portofolio tahunan
    # Annualize mean daily returns first
    annual_returns_individual = mean_daily_returns * TRADING_DAYS_PER_YEAR
    portfolio_annual_return = np.sum(annual_returns_individual * weights)
    portfolio_returns.append(portfolio_annual_return)

    # c. Hitung volatilitas portofolio tahunan
    # Annualize covariance matrix by multiplying by TRADING_DAYS_PER_YEAR
    portfolio_annual_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix_daily * TRADING_DAYS_PER_YEAR, weights)))
    portfolio_volatility.append(portfolio_annual_volatility)

    # d. Hitung Sharpe Ratio portofolio
    sharpe_ratio = (portfolio_annual_return - RISK_FREE_RATE) / portfolio_annual_volatility
    portfolio_sharpe_ratios.append(sharpe_ratio)

# 4. Buat DataFrame dari hasil simulasi
portfolio_results = pd.DataFrame({
    'Return': portfolio_returns,
    'Volatility': portfolio_volatility,
    'Sharpe Ratio': portfolio_sharpe_ratios
})

# Tambahkan kolom bobot ke DataFrame
for i, col in enumerate(daily_returns.columns):
    portfolio_results[col + ' Weight'] = [w[i] for w in portfolio_weights]

print("Lima baris pertama hasil simulasi portofolio:")
print(portfolio_results.head())

# 5. Identifikasi portofolio optimal dan risiko minimum
# Portofolio dengan Sharpe Ratio tertinggi
optimal_portfolio = portfolio_results.loc[portfolio_results['Sharpe Ratio'].idxmax()]

# Portofolio dengan volatilitas terendah
min_volatility_portfolio = portfolio_results.loc[portfolio_results['Volatility'].idxmin()]

# 6. Cetak metrik untuk portofolio optimal dan risiko minimum
print("\n======================================================")
print("Portofolio Optimal (Sharpe Ratio Tertinggi):")
print("------------------------------------------------------")
print(f"Annual Return: {optimal_portfolio['Return']:.4f}")
print(f"Annualized Volatility: {optimal_portfolio['Volatility']:.4f}")
print(f"Sharpe Ratio: {optimal_portfolio['Sharpe Ratio']:.4f}")
print("Weights:")
for col in daily_returns.columns:
    print(f"  {col}: {optimal_portfolio[col + ' Weight']:.4f}")
print("======================================================")

print("\n======================================================")
print("Portofolio Risiko Minimum:")
print("------------------------------------------------------")
print(f"Annual Return: {min_volatility_portfolio['Return']:.4f}")
print(f"Annualized Volatility: {min_volatility_portfolio['Volatility']:.4f}")
print(f"Sharpe Ratio: {min_volatility_portfolio['Sharpe Ratio']:.4f}")
print("Weights:")
for col in daily_returns.columns:
    print(f"  {col}: {min_volatility_portfolio[col + ' Weight']:.4f}")
print("======================================================")

display(portfolio_results)

"""## **Visualisasi Hasil Analisis Portofolio**"""

import seaborn as sns

# 1. Buat scatter plot dari semua portofolio yang disimulasikan
plt.figure(figsize=(12, 8))

# Scatter plot untuk semua portofolio
scatter = plt.scatter(
    portfolio_results['Volatility'],
    portfolio_results['Return'],
    c=portfolio_results['Sharpe Ratio'], # Warna berdasarkan Sharpe Ratio
    cmap='viridis', # Colormap
    marker='o',
    s=10, # Ukuran marker
    alpha=0.7,
    label='Simulated Portfolios'
)

# 2. Tandai portofolio optimal (Sharpe Ratio tertinggi)
plt.scatter(
    optimal_portfolio['Volatility'],
    optimal_portfolio['Return'],
    marker='*', # Penanda bintang
    color='red',
    s=300, # Ukuran lebih besar
    label='Optimal Portfolio (Max Sharpe Ratio)',
    edgecolors='black',
    linewidth=1
)

# 3. Tandai portofolio risiko minimum
plt.scatter(
    min_volatility_portfolio['Volatility'],
    min_volatility_portfolio['Return'],
    marker='*', # Penanda bintang
    color='green',
    s=300, # Ukuran lebih besar
    label='Minimum Volatility Portfolio',
    edgecolors='black',
    linewidth=1
)

# 4. Tambahkan judul plot dan label sumbu
plt.title('Efficient Frontier dengan Simulasi Monte Carlo', fontsize=16)
plt.xlabel('Volatilitas Tahunan (Standar Deviasi)', fontsize=12)
plt.ylabel('Return Tahunan', fontsize=12)

# 5. Tampilkan legenda dan grid
plt.legend(labelspacing=0.8, loc='best')
plt.grid(True, linestyle='--', alpha=0.6)

# Tambahkan color bar untuk Sharpe Ratio
cbar = plt.colorbar(scatter)
cbar.set_label('Sharpe Ratio', rotation=270, labelpad=20)

# Tampilkan plot
plt.tight_layout()
plt.show()

print("Scatter plot hasil simulasi portofolio telah ditampilkan.")